FROM node:14

WORKDIR /usr/src/app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем все файлы проекта
COPY . .

EXPOSE 3000
CMD ["node", "./DockerCompose/server.js"]
