version: '3.7' # Убедитесь, что версия поддерживает условия

services:
  web:
    build: ./web
    ports:
      - "8080:80"
    volumes:
      - ./web/public:/usr/local/apache2/htdocs
    networks:
      - my_network
    depends_on:
      - api
      - db

  api:
    build: ./api
    ports:
      - "3001:3001"
    networks:
      - my_network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - db_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  my_network:
    external: true
